name = "kyrorblx/lori"
version = "0.0.5"
description = "Small Roblox debug UI library"
license = "MIT"
authors = ["KYRORBLX <dullflowerr>"]
repository = "https://github.com/KYRORBLX/Lori"
includes = [
	"default.project.json",
	"LICENSE",
	"README.md",
	"src/**/*.luau",
	"typings/**/*.d.ts",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
